[profile.default]
src = 'packages'
test = 'packages'
script = 'scripts'
out = 'out'
libs = ["node_modules", "lib"]
cache_path = 'cache'
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

# Dependencies - using npm packages
remappings = [
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    'forge-std/=node_modules/forge-std/src/',
    '@pythnetwork/pyth-sdk-solidity/=node_modules/@pythnetwork/pyth-sdk-solidity/',
    '@prb-math/=node_modules/@prb/math/src/',
    'fvm-solidity/=lib/fvm-solidity/src/',
    # Cross-package imports as per original proposal
    '@filoz/pay/=packages/pay/src/',
    '@filoz/pdp/=packages/pdp/src/',
    '@filoz/session-key-registry/=packages/session-key-registry/src/',
    '@filoz/warm-storage/=packages/warm-storage/src/',
    # Legacy aliases for backward compatibility
    '@fws-payments/=packages/pay/src/',
    '@pdp/=packages/pdp/src/',
    '@session-key-registry/=packages/session-key-registry/src/',
    '@warm-storage/=packages/warm-storage/src/',
]

# Allow reading test data files
fs_permissions = [
    { access = "read", path = "./packages" },
    { access = "read", path = "./test" }
]

[lint]
exclude_lints = [
    "asm-keccak256",
    "incorrect-shift", 
    "mixed-case-function",
    "mixed-case-variable",
    "pascal-case-struct",
    "screaming-snake-case-immutable",
]
