name: Check ABI consistency

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-abi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.2.3

      - name: Install dependencies
        run: | 
          cd service_contracts
          forge install

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Check ABI consistency
        run: |
          cd service_contracts
          make abi
          git diff --exit-code subgraph/abis/ || (echo "ABI files are not consistent. Please run 'make abi' inside service_contracts."; exit 1)